version: '2.1'

services:
  bot:
    image: bot
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
      - PHONE=${PHONE}
      - VIDEO_DIR=/video
      - CONFIG_DIR=/config
      - SESSION_STRING=${SESSION_STRING}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ENGINE=${OPENAI_ENGINE}
    volumes:
      - ./data/config:/config
      - type: bind
        source: /mnt/hdd/plex/tv/one_piece
        target: /video
        bind:
          propagation: shared

    restart: always
